const resList = [
       {
              info: {
                     id: 43931,
                     name: "Baskin Robbins - Ice Cream Desserts",
                     cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
                     locality: "Opposite Mumbai university main gate",
                     areaName: "Santacruz East",
                     costForTwo: "₹350 for two",
                     cuisines: ["Ice Cream", "Desserts"],
                     avgRating: 4.7,
                     veg: true,
                     parentId: 5588,
                     avgRatingString: 4.7,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 26,
                            lastMileTravel: 3.6,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "3.6 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "40% OFF",
                            subHeader: "UPTO ₹80",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/baskin-robbins-ice-cream-desserts-opposite-university-main-gate-santacruz-east-mumbai-43931",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 78036,
                     name: "Burger King",
                     cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
                     locality: "Central Plaza, Kalina",
                     areaName: "Santacruz East",
                     costForTwo: "₹350 for two",
                     cuisines: ["Burgers", "American"],
                     avgRating: 4.3,
                     parentId: 166,
                     avgRatingString: 4.3,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 29,
                            lastMileTravel: 2.9,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "2.9 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 05:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/burger-king-central-plaza-kalina-santacruz-east-mumbai-78036",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 52767,
                     name: "KFC",
                     cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
                     locality: "Sakinaka",
                     areaName: "Saki Naka",
                     costForTwo: "₹400 for two",
                     cuisines: [
                            "Burgers",
                            "Biryani",
                            "American",
                            "Snacks",
                            "Fast Food",
                     ],
                     avgRating: 4.3,
                     parentId: 547,
                     avgRatingString: 4.3,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 26,
                            lastMileTravel: 4.5,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "4.5 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 02:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "20% OFF",
                            subHeader: "UPTO ₹50",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/kfc-sakinaka-saki-naka-mumbai-52767",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 23758,
                     name: "McDonald's",
                     cloudinaryImageId: "03501c33ecb3a3105124441e541e6fe4",
                     locality: "M G Road",
                     areaName: "Kurla",
                     costForTwo: "₹400 for two",
                     cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
                     avgRating: 4.3,
                     parentId: 630,
                     avgRatingString: 4.3,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 27,
                            lastMileTravel: 4.4,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "4.4 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 02:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     aggregatedDiscountInfoV2: {},
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/mcdonalds-m-g-road-kurla-mumbai-23758",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 391816,
                     name: "Louis Burger",
                     cloudinaryImageId: "19d3d352cc815b9d88b22617b41fa97b",
                     locality: "Trade Centre",
                     areaName: "Santacruz Bandra east",
                     costForTwo: "₹600 for two",
                     cuisines: ["Burgers", "American", "Fast Food"],
                     avgRating: 4.4,
                     parentId: 22485,
                     avgRatingString: 4.4,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 29,
                            lastMileTravel: 2.1,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "2.1 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "₹125 OFF",
                            subHeader: "ABOVE ₹249",
                            discountTag: "FLAT DEAL",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/louis-burger-trade-centre-santacruz-bandra-east-mumbai-391816",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 9052,
                     name: "Subway",
                     cloudinaryImageId: "63178e3e64d503a479f2a2048a474552",
                     locality: "Central Plaza, Kalina",
                     areaName: "Santacruz East",
                     costForTwo: "₹350 for two",
                     cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
                     avgRating: 4.3,
                     parentId: 2,
                     avgRatingString: 4.3,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 27,
                            lastMileTravel: 2.9,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "2.9 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "40% OFF",
                            subHeader: "UPTO ₹80",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/subway-central-plaza-kalina-santacruz-east-mumbai-9052",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 364099,
                     name: "Sassy Teaspoon",
                     cloudinaryImageId: "bc63cb014055874144f4a89b560a8df7",
                     locality: "Chembur",
                     areaName: "Chembur",
                     costForTwo: "₹300 for two",
                     cuisines: ["Desserts", "Bakery"],
                     avgRating: 4.3,
                     parentId: 3601,
                     avgRatingString: 4.3,
                     totalRatingsString: "500+",
                     sla: {
                            deliveryTime: 25,
                            lastMileTravel: 5,
                            serviceability: "SERVICEABLE",
                            slaString: "20-25 mins",
                            lastMileTravelString: "5.0 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 03:00:00",
                            opened: true,
                     },
                     badges: {
                            textExtendedBadges: [
                                   {
                                          iconId: "v1705582451/Ratnesh_Badges/Listing_HR.png",
                                          shortDescription:
                                                 "Perfect Cake Delivery",
                                          fontColor: "#7E808C",
                                   },
                            ],
                     },
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {
                                          badgeObject: [
                                                 {
                                                        attributes: {
                                                               description: 0,
                                                               fontColor: "#7E808C",
                                                               iconId: "v1705582451/Ratnesh_Badges/Listing_HR.png",
                                                               shortDescription:
                                                                      "Perfect Cake Delivery",
                                                        },
                                                 },
                                          ],
                                   },
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "20% OFF",
                            subHeader: "UPTO ₹50",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/sassy-teaspoon-chembur-mumbai-364099",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 421377,
                     name: "Tru Falafel",
                     cloudinaryImageId: "3656a459e0ba179e250cf25836d02134",
                     locality: "Ra Industrial Complex",
                     areaName: "Marol Sakinaka",
                     costForTwo: "₹600 for two",
                     cuisines: [
                            "Lebanese",
                            "Rolls & Wraps",
                            "Arabian",
                            "Fast Food",
                            "Mediterranean",
                            "Desserts",
                            "Beverages",
                     ],
                     avgRating: 4.4,
                     parentId: 234397,
                     avgRatingString: 4.4,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 34,
                            lastMileTravel: 6.7,
                            serviceability: "SERVICEABLE",
                            slaString: "30-35 mins",
                            lastMileTravelString: "6.7 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 03:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "50% OFF",
                            subHeader: "UPTO ₹100",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/tru-falafel-ra-industrial-complex-marol-sakinaka-mumbai-421377",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 3279,
                     name: "5 Spice",
                     cloudinaryImageId: "jkrmrzoxcwnpwievotlz",
                     locality: "Sakinaka",
                     areaName: "Marol Sakinaka",
                     costForTwo: "₹750 for two",
                     cuisines: ["Chinese", "Asian", "Thai", "Seafood"],
                     avgRating: 4.3,
                     parentId: 15,
                     avgRatingString: 4.3,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 29,
                            lastMileTravel: 5,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "5.0 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 02:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/5-spice-sakinaka-marol-sakinaka-mumbai-3279",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 433058,
                     name: "Nino Burgers",
                     cloudinaryImageId: "9e9bd2c9ca7be7c08e88ccf1eeccfb1e",
                     locality: "Marol",
                     areaName: "Marol ",
                     costForTwo: "₹500 for two",
                     cuisines: ["American", "Burgers", "Fast Food"],
                     avgRating: 4.3,
                     parentId: 12333,
                     avgRatingString: 4.3,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 33,
                            lastMileTravel: 6.3,
                            serviceability: "SERVICEABLE",
                            slaString: "30-35 mins",
                            lastMileTravelString: "6.3 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/nino-burgers-marol-mumbai-433058",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 15321,
                     name: "Charcoal Eats - Biryani & Beyond",
                     cloudinaryImageId: "9c18db360f5bee01412a495b1a67372d",
                     locality: "Patil Wadi",
                     areaName: "Chembur",
                     costForTwo: "₹499 for two",
                     cuisines: ["Biryani", "Kebabs", "North Indian", "Mughlai"],
                     avgRating: 4.3,
                     parentId: 5338,
                     avgRatingString: 4.3,
                     totalRatingsString: "5K+",
                     sla: {
                            deliveryTime: 35,
                            lastMileTravel: 6.7,
                            serviceability: "SERVICEABLE",
                            slaString: "35-40 mins",
                            lastMileTravelString: "6.7 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 02:45:00",
                            opened: true,
                     },
                     badges: {
                            textExtendedBadges: [
                                   {
                                          iconId: "guiltfree/GF_Logo_android_3x",
                                          shortDescription: "options available",
                                          fontColor: "#7E808C",
                                   },
                            ],
                     },
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {
                                          badgeObject: [
                                                 {
                                                        attributes: {
                                                               description: 0,
                                                               fontColor: "#7E808C",
                                                               iconId: "guiltfree/GF_Logo_android_3x",
                                                               shortDescription:
                                                                      "options available",
                                                        },
                                                 },
                                          ],
                                   },
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "50% OFF",
                            subHeader: "UPTO ₹100",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/charcoal-eats-biryani-and-beyond-patil-wadi-chembur-mumbai-15321",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 48056,
                     name: "Cheelizza - India Ka Pizza",
                     cloudinaryImageId: "f58a1b772e5eeea45ff8ead3890703ed",
                     locality: "Sakinaka",
                     areaName: "Sakinaka",
                     costForTwo: "₹500 for two",
                     cuisines: ["Pizzas", "Italian", "Fast Food"],
                     avgRating: 4.3,
                     veg: true,
                     parentId: 375077,
                     avgRatingString: 4.3,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 33,
                            lastMileTravel: 5,
                            serviceability: "SERVICEABLE",
                            slaString: "30-35 mins",
                            lastMileTravelString: "5.0 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 03:00:00",
                            opened: true,
                     },
                     badges: {
                            imageBadges: [
                                   {
                                          imageId: "v1695133679/badges/Pure_Veg111.png",
                                          description: "pureveg",
                                   },
                            ],
                            textExtendedBadges: [
                                   {
                                          iconId: "guiltfree/GF_Logo_android_3x",
                                          shortDescription: "options available",
                                          fontColor: "#7E808C",
                                   },
                            ],
                     },
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {
                                          badgeObject: [
                                                 {
                                                        attributes: {
                                                               description:
                                                                      "pureveg",
                                                               imageId: "v1695133679/badges/Pure_Veg111.png",
                                                        },
                                                 },
                                          ],
                                   },
                                   textBased: {},
                                   textExtendedBadges: {
                                          badgeObject: [
                                                 {
                                                        attributes: {
                                                               description: 0,
                                                               fontColor: "#7E808C",
                                                               iconId: "guiltfree/GF_Logo_android_3x",
                                                               shortDescription:
                                                                      "options available",
                                                        },
                                                 },
                                          ],
                                   },
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/cheelizza-india-ka-pizza-sakinaka-mumbai-48056",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 433800,
                     name: "1441 Pizzeria",
                     cloudinaryImageId: "c7fcd9e43f4b995c3cd08d7632b426f0",
                     locality: "Main Road",
                     areaName: "Sion",
                     costForTwo: "₹500 for two",
                     cuisines: ["Italian", "Pizzas", "Pastas"],
                     avgRating: 4.1,
                     parentId: 2697,
                     avgRatingString: 4.1,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 36,
                            lastMileTravel: 6.5,
                            serviceability: "SERVICEABLE",
                            slaString: "35-40 mins",
                            lastMileTravelString: "6.5 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/1441-pizzeria-main-road-sion-mumbai-433800",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 221303,
                     name: "NOTO - Ice Creams & Desserts",
                     cloudinaryImageId: "81ac87e5c89c16adc867be38ce5a1ba3",
                     locality: "Powai Area",
                     areaName: "Powai",
                     costForTwo: "₹300 for two",
                     cuisines: ["Ice Cream", "Healthy Food"],
                     avgRating: 4.5,
                     veg: true,
                     parentId: 468478,
                     avgRatingString: 4.5,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 34,
                            lastMileTravel: 8.2,
                            serviceability: "SERVICEABLE",
                            slaString: "30-35 mins",
                            lastMileTravelString: "8.2 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 03:30:00",
                            opened: true,
                     },
                     badges: {
                            textExtendedBadges: [
                                   {
                                          iconId: "guiltfree/GF_Logo_android_3x",
                                          shortDescription: "brand",
                                          fontColor: "#7E808C",
                                   },
                            ],
                     },
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {
                                          badgeObject: [
                                                 {
                                                        attributes: {
                                                               description: 0,
                                                               fontColor: "#7E808C",
                                                               iconId: "guiltfree/GF_Logo_android_3x",
                                                               shortDescription:
                                                                      "brand",
                                                        },
                                                 },
                                          ],
                                   },
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/noto-ice-creams-and-desserts-area-powai-mumbai-221303",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 32775,
                     name: "Pizza Caprina",
                     cloudinaryImageId: "n85fpmfr0z5ywpjrrfom",
                     locality: "Subhash Nagar",
                     areaName: "Chembur",
                     costForTwo: "₹600 for two",
                     cuisines: ["Pizzas", "Pastas", "Burgers", "Desserts"],
                     avgRating: 4.2,
                     parentId: 720,
                     avgRatingString: 4.2,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 32,
                            lastMileTravel: 5,
                            serviceability: "SERVICEABLE",
                            slaString: "30-35 mins",
                            lastMileTravelString: "5.0 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 03:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/pizza-caprina-subhash-nagar-chembur-mumbai-32775",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 433120,
                     name: "Francesco's Pizzeria",
                     cloudinaryImageId: "956ffaf61170ebd6eb35ecc906b51d8e",
                     locality: "Marol",
                     areaName: "Marol",
                     costForTwo: "₹600 for two",
                     cuisines: ["Pizzas", "Italian", "Fast Food"],
                     avgRating: 4.3,
                     parentId: 2464,
                     avgRatingString: 4.3,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 37,
                            lastMileTravel: 6.3,
                            serviceability: "SERVICEABLE",
                            slaString: "35-40 mins",
                            lastMileTravelString: "6.3 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/francescos-pizzeria-marol-mumbai-433120",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 6632,
                     name: "Ice Cream Works",
                     cloudinaryImageId: "otwhttiu0xzotfi7meqk",
                     locality: "Dadar West",
                     areaName: "Dadar West",
                     costForTwo: "₹300 for two",
                     cuisines: ["Ice Cream", "Desserts", "Beverages"],
                     avgRating: 4.6,
                     veg: true,
                     parentId: 491,
                     avgRatingString: 4.6,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 31,
                            lastMileTravel: 9.3,
                            serviceability: "SERVICEABLE",
                            slaString: "30-35 mins",
                            lastMileTravelString: "9.3 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 03:30:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "40% OFF",
                            subHeader: "UPTO ₹80",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/ice-cream-works-dadar-west-mumbai-6632",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 203641,
                     name: "Wakka Makka Chinese",
                     cloudinaryImageId: "dwk48ybfhoilp6jlxwpd",
                     locality: "Nandadham Industrial Estate",
                     areaName: "Marol, Mumbai",
                     costForTwo: "₹250 for two",
                     cuisines: ["Chinese", "Asian", "Thai", "Beverages"],
                     avgRating: 4.2,
                     parentId: 288250,
                     avgRatingString: 4.2,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 35,
                            lastMileTravel: 6,
                            serviceability: "SERVICEABLE",
                            slaString: "35-40 mins",
                            lastMileTravelString: "6.0 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 07:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "50% OFF",
                            subHeader: "UPTO ₹100",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/wakka-makka-chinese-nandadham-industrial-estate-marol-mumbai-mumbai-203641",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 228188,
                     name: "Wack Waffles & Brownies",
                     cloudinaryImageId: "afniisy7ene3lmhgqjh3",
                     locality: "Nandadham Industrial Estate",
                     areaName: "Marol, Mumbai",
                     costForTwo: "₹250 for two",
                     cuisines: ["Waffle", "Desserts", "Bakery", "Beverages"],
                     avgRating: 4.3,
                     veg: true,
                     parentId: 382937,
                     avgRatingString: 4.3,
                     totalRatingsString: "500+",
                     sla: {
                            deliveryTime: 35,
                            lastMileTravel: 6,
                            serviceability: "SERVICEABLE",
                            slaString: "35-40 mins",
                            lastMileTravelString: "6.0 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 06:00:00",
                            opened: true,
                     },
                     badges: {
                            imageBadges: [
                                   {
                                          imageId: "v1695133679/badges/Pure_Veg111.png",
                                          description: "pureveg",
                                   },
                            ],
                     },
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {
                                          badgeObject: [
                                                 {
                                                        attributes: {
                                                               description:
                                                                      "pureveg",
                                                               imageId: "v1695133679/badges/Pure_Veg111.png",
                                                        },
                                                 },
                                          ],
                                   },
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/wack-waffles-and-brownies-nandadham-industrial-estate-marol-mumbai-mumbai-228188",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 628550,
                     name: "The Brooklyn Creamery - Healthy Ice Cream",
                     cloudinaryImageId: "b1b35780a9b1dfeb26d680506d494eaa",
                     locality: "Saki Vihar Road",
                     areaName: "Chandivali",
                     costForTwo: "₹200 for two",
                     cuisines: ["Desserts", "Ice Cream", "Healthy Food"],
                     avgRating: 4.5,
                     veg: true,
                     parentId: 236673,
                     avgRatingString: 4.5,
                     totalRatingsString: "100+",
                     sla: {
                            deliveryTime: 28,
                            lastMileTravel: 6.3,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "6.3 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 02:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "50% OFF",
                            subHeader: "UPTO ₹100",
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {},
              cta: {
                     link: "https://www.swiggy.com/restaurants/the-brooklyn-creamery-healthy-ice-cream-saki-vihar-road-chandivali-mumbai-628550",
                     type: "WEBLINK",
              },
       },
       {
              info: {
                     id: 387322,
                     name: "La Pino'z Pizza",
                     cloudinaryImageId: "pf3fw4qzazsu0dqngrry",
                     locality: "Mg Road",
                     areaName: "Ghatkopar Vikhroli",
                     costForTwo: "₹300 for two",
                     cuisines: [
                            "Pizzas",
                            "Pastas",
                            "Italian",
                            "Desserts",
                            "Beverages",
                     ],
                     avgRating: 4.1,
                     veg: true,
                     parentId: 4961,
                     avgRatingString: 4.1,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 29,
                            lastMileTravel: 4.2,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "4.2 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 02:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "40% OFF",
                            subHeader: "UPTO ₹80",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/la-pinoz-pizza-mg-road-ghatkopar-vikhroli-mumbai-387322",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
       {
              info: {
                     id: 43931,
                     name: "Baskin Robbins - Ice Cream Desserts",
                     cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
                     locality: "Opposite Mumbai university main gate",
                     areaName: "Santacruz East",
                     costForTwo: "₹350 for two",
                     cuisines: ["Ice Cream", "Desserts"],
                     avgRating: 4.7,
                     veg: true,
                     parentId: 5588,
                     avgRatingString: 4.7,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 26,
                            lastMileTravel: 3.6,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "3.6 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "40% OFF",
                            subHeader: "UPTO ₹80",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/baskin-robbins-ice-cream-desserts-opposite-university-main-gate-santacruz-east-mumbai-43931",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
       {
              info: {
                     id: 651641,
                     name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
                     cloudinaryImageId: "909daf097e30cd01d8fd121ddc6de2f6",
                     locality: "Andheri-kurla Road",
                     areaName: "Marol Sakinaka",
                     costForTwo: "₹200 for two",
                     cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
                     avgRating: 4.5,
                     veg: true,
                     parentId: 582,
                     avgRatingString: 4.5,
                     totalRatingsString: "50+",
                     sla: {
                            deliveryTime: 26,
                            lastMileTravel: 5,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "5.0 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 03:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "50% OFF",
                            subHeader: "UPTO ₹100",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/kwality-walls-frozen-dessert-and-ice-cream-shop-andheri-kurla-road-marol-sakinaka-mumbai-651641",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
       {
              info: {
                     id: 106763,
                     name: "Rangoon Zaika",
                     cloudinaryImageId: "o5bbufmcjoqdfvtm7r1n",
                     locality: "Kurla East",
                     areaName: "Kurla West",
                     costForTwo: "₹400 for two",
                     cuisines: ["Indian", "Chinese"],
                     avgRating: 3.9,
                     parentId: 166932,
                     avgRatingString: 3.9,
                     totalRatingsString: "5K+",
                     sla: {
                            deliveryTime: 22,
                            lastMileTravel: 1.1,
                            serviceability: "SERVICEABLE",
                            slaString: "20-25 mins",
                            lastMileTravelString: "1.1 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 05:30:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "20% OFF",
                            subHeader: "UPTO ₹50",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/rangoon-zaika-kurla-east-kurla-west-mumbai-106763",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
       {
              info: {
                     id: 78036,
                     name: "Burger King",
                     cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
                     locality: "Central Plaza, Kalina",
                     areaName: "Santacruz East",
                     costForTwo: "₹350 for two",
                     cuisines: ["Burgers", "American"],
                     avgRating: 4.3,
                     parentId: 166,
                     avgRatingString: 4.3,
                     totalRatingsString: "10K+",
                     sla: {
                            deliveryTime: 29,
                            lastMileTravel: 2.9,
                            serviceability: "SERVICEABLE",
                            slaString: "25-30 mins",
                            lastMileTravelString: "2.9 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 05:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/burger-king-central-plaza-kalina-santacruz-east-mumbai-78036",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
       {
              info: {
                     id: 6663,
                     name: "Mughal Dhaba",
                     cloudinaryImageId: "df600a304a4c328795e659b072d93208",
                     locality: "LBS Marg, Kurla West",
                     areaName: "Kurla West",
                     costForTwo: "₹500 for two",
                     cuisines: ["Mughlai", "Chinese"],
                     avgRating: 4.1,
                     parentId: 140929,
                     avgRatingString: 4.1,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 24,
                            lastMileTravel: 1.1,
                            serviceability: "SERVICEABLE",
                            slaString: "20-25 mins",
                            lastMileTravelString: "1.1 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 05:30:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "40% OFF",
                            subHeader: "UPTO ₹75",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/mughal-dhaba-lbs-marg-kurla-west-mumbai-6663",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
       {
              info: {
                     id: 303850,
                     name: "Janata Tawa And Grill",
                     cloudinaryImageId: "zrusx2rcjtsxpksm4lne",
                     locality: "Kurla West",
                     areaName: "Kurla West",
                     costForTwo: "₹500 for two",
                     cuisines: ["Indian", "Chinese", "Tandoor"],
                     avgRating: 4.4,
                     parentId: 109562,
                     avgRatingString: 4.4,
                     totalRatingsString: "1K+",
                     sla: {
                            deliveryTime: 22,
                            lastMileTravel: 1,
                            serviceability: "SERVICEABLE",
                            slaString: "20-25 mins",
                            lastMileTravelString: "1.0 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:30:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "10% OFF",
                            subHeader: "UPTO ₹40",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/janata-tawa-and-grill-kurla-west-mumbai-303850",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
       {
              info: {
                     id: 111518,
                     name: "Kurla Juicy Hut",
                     cloudinaryImageId: "s6fhwzl0tss0vgrqvcid",
                     locality: "Kurla",
                     areaName: "Kurla West",
                     costForTwo: "₹300 for two",
                     cuisines: ["Beverages", "Desserts"],
                     avgRating: 4.2,
                     parentId: 121989,
                     avgRatingString: 4.2,
                     totalRatingsString: "5K+",
                     sla: {
                            deliveryTime: 19,
                            lastMileTravel: 1.1,
                            serviceability: "SERVICEABLE",
                            slaString: "15-20 mins",
                            lastMileTravelString: "1.1 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 05:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "10% OFF",
                            subHeader: "ABOVE ₹700",
                            discountTag: "FLAT DEAL",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/kurla-juicy-hut-kurla-kurla-west-mumbai-111518",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
       {
              info: {
                     id: 802336,
                     name: "Yasin's Food Inn",
                     cloudinaryImageId: "ad71e7632fb460a2559b64289ec9c2b2",
                     locality: "Radhabai Niwas Corner",
                     areaName: "Kurla",
                     costForTwo: "₹300 for two",
                     cuisines: [
                            "North Indian",
                            "Chinese",
                            "Mughlai",
                            "Fast Food",
                            "Biryani",
                            "Beverages",
                     ],
                     avgRating: 4.3,
                     parentId: 313916,
                     avgRatingString: 4.3,
                     totalRatingsString: "100+",
                     sla: {
                            deliveryTime: 20,
                            lastMileTravel: 1.1,
                            serviceability: "SERVICEABLE",
                            slaString: "20-25 mins",
                            lastMileTravelString: "1.1 km",
                            iconType: "ICON_TYPE_EMPTY",
                     },
                     availability: {
                            nextCloseTime: "2024-03-19 04:00:00",
                            opened: true,
                     },
                     badges: {},
                     isOpen: true,
                     type: "F",
                     badgesV2: {
                            entityBadges: {
                                   imageBased: {},
                                   textBased: {},
                                   textExtendedBadges: {},
                            },
                     },
                     aggregatedDiscountInfoV3: {
                            header: "60% OFF",
                            subHeader: "UPTO ₹120",
                     },
                     orderabilityCommunication: {
                            title: {},
                            subTitle: {},
                            message: {},
                            customIcon: {},
                     },
                     differentiatedUi: {
                            displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                            differentiatedUiMediaDetails: {
                                   mediaType: "ADS_MEDIA_ENUM_IMAGE",
                                   lottie: {},
                                   video: {},
                            },
                     },
                     reviewsSummary: {},
                     displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                     isNewlyOnboarded: true,
                     restaurantOfferPresentationInfo: {},
              },
              analytics: {
                     context: "seo-data-39370cd1-c856-41e3-ba74-5771ba21916e",
              },
              cta: {
                     link: "https://www.swiggy.com/restaurants/yasins-food-inn-radhabai-niwas-corner-kurla-mumbai-802336",
                     text: "RESTAURANT_MENU",
                     type: "WEBLINK",
              },
              widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
       },
];

export default resList;  